version: "3.9"  
services:
  my-django:
  
    container_name: django_docker
    image: 6democratickim9/django_docker
    ports:
      - 8800:8000
    depends_on:
      - my-mysql
    networks: 
      - "my-network"

  my-mysql:
    container_name: mysql
    image: 6democratickim9/mysql:5.7
    # volumes: 
    #   - ./mysql-data:/var/lib/mysql
    ports: 
      - 13306:3306
    environment: 
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: 1234
    networks: 
      - "my-network"



networks:
  my-network:
    driver: bridge
