# Generated by Django 3.1.6 on 2021-02-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_news',
            name='preview',
            field=models.CharField(max_length=500, unique=True, verbose_name='preview'),
        ),
    ]
